---
apiVersion: infra.whiz.ai/v1
kind: AIGen
metadata:
  name: aigen
  namespace: default
spec:
  targetNamespace: test
  cpuDeployment: whiz-ai-gen-cpu
  gpuDeployment: whiz-ai-gen-gpu
  replicas: 2
