apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aigens.infra.whiz.ai
spec:
  group: infra.whiz.ai
  scope: Namespaced
  names:
    plural: aigens
    singular: aigen
    kind: AIGen
    shortNames:
      - aigen
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Active Deployment
          type: string
          jsonPath: .status.activeDeployment
        - name: Namespace
          type: string
          jsonPath: .status.activeNamespace
        - name: Last Sync
          type: string
          jsonPath: .status.lastSyncTime
        - name: Reason
          type: string
          jsonPath: .status.reason
        - name: Age                       # <-- Added
          type: date                      # <-- Required so kubectl formats it
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetNamespace:
                  type: string
                whizCpuDeployment:
                  type: string
                whizGpuDeployment:
                  type: string
            status:
              type: object
              properties:
                lastSyncTime:
                  type: string
                activeDeployment:
                  type: string
                activeNamespace:
                  type: string
                reason:
                  type: string
