apiVersion: infra.whiz.ai/v1
kind: AIGen
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: {{ .Release.Namespace }}
  cpuDeployment: {{ .Release.Name}}-whiz-ai-gen-cpu
  gpuDeployment: {{ .Release.Name}}-whiz-ai-gen-gpu
  replicas: {{ .Values.replicas }}
