
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-aigen-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aigen-operator
  template:
    metadata:
      labels:
        app: aigen-operator
    spec:
      serviceAccountName: {{ .Release.Name }}-aigen-operator
      containers:
      - name: operator
        # image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        image: ahmaddilshad18/game:07
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: RECONCILE_INTERVAL
          value: "120"
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
